using System;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using ProjetosCADLaser.Models;
using ProjetosCADLaser.Services;

namespace ProjetosCADLaser.Forms
{
    public sealed partial class TesteTexturaForm : Form
    {
        private readonly AppServices _servicos; private readonly ConfiguracaoLocal _local; private readonly TextBox _identificacao = new TextBox { Width = 300 }; private readonly TextBox _origem = new TextBox { Width = 360, ReadOnly = true }; private readonly TextBox _observacao = new TextBox { Width = 360 }; private readonly Label _imagem = new Label { AutoSize = true, Text = "Nenhuma imagem selecionada" }; private AnexoPendente _imagemPendente; private readonly string _sessao;
        public TesteTexturaForm(AppServices servicos, ConfiguracaoLocal local) { _servicos = servicos; _local = local; _sessao = servicos.Anexos.CriarSessao(); Text = "Teste de textura"; Size = new Size(700, 380); var layout = new TableLayoutPanel { Dock = DockStyle.Fill, Padding = new Padding(24), ColumnCount = 2, RowCount = 6 }; layout.Controls.Add(new Label { Text = "Identificação", AutoSize = true }, 0, 0); layout.Controls.Add(_identificacao, 1, 0); layout.Controls.Add(new Label { Text = "Pasta de origem", AutoSize = true }, 0, 1); var escolherPasta = new Button { Text = "Selecionar pasta", AutoSize = true }; escolherPasta.Click += delegate { using (var d = new FolderBrowserDialog()) if (d.ShowDialog(this) == DialogResult.OK) _origem.Text = d.SelectedPath; }; layout.Controls.Add(escolherPasta, 1, 1); layout.Controls.Add(new Label { Text = "Observação", AutoSize = true }, 0, 2); layout.Controls.Add(_observacao, 1, 2); var escolherImagem = new Button { Text = "Selecionar imagem obrigatória", AutoSize = true }; escolherImagem.Click += delegate { AdicionarImagem(); }; layout.Controls.Add(escolherImagem, 0, 3); layout.Controls.Add(_imagem, 1, 3); var salvar = new Button { Text = "Salvar teste", AutoSize = true }; salvar.Click += delegate { Salvar(); }; var cancelar = new Button { Text = "Cancelar", AutoSize = true }; cancelar.Click += delegate { Close(); }; var botoes = new FlowLayoutPanel { AutoSize = true }; botoes.Controls.Add(cancelar); botoes.Controls.Add(salvar); layout.Controls.Add(botoes, 1, 4); Controls.Add(layout); FormClosed += delegate { try { servicos.Anexos.LimparSessao(_sessao); } catch { } }; servicos.Tema.Aplicar(this); }
        private void AdicionarImagem() { using (var d = new OpenFileDialog { Filter = "Imagens|*.png;*.jpg;*.jpeg;*.bmp;*.gif" }) if (d.ShowDialog(this) == DialogResult.OK) try { _imagemPendente = _servicos.Anexos.AdicionarArquivo(_sessao, d.FileName, true); _imagem.Text = _imagemPendente.NomeOriginal; } catch (IOException ex) { MessageBox.Show(this, ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Warning); } }
        private void Salvar() { try { if (string.IsNullOrWhiteSpace(_imagemPendente == null ? null : _imagemPendente.CaminhoTemporario)) throw new InvalidDataException("Selecione a imagem obrigatória."); var teste = _servicos.TestesTextura.Cadastrar(_local.PastaRaizDados, _identificacao.Text, _origem.Text, StatusTesteTextura.EmTeste, null, _observacao.Text, _imagemPendente, new System.Collections.Generic.List<AnexoPendente>()); DialogResult = DialogResult.OK; Close(); } catch (Exception ex) when (ex is InvalidDataException || ex is IOException || ex is ArgumentException) { _servicos.Log.Registrar(ex, "Falha no cadastro do teste de textura", _local.PastaRaizDados); MessageBox.Show(this, ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Warning); } }
    }
}
