using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using ProjetosCADLaser.Models;

namespace ProjetosCADLaser.Services
{
    public sealed class EdicaoAnexoTeste { public string Titulo { get; private set; } public string Categoria { get; private set; } public bool Remover { get; private set; } public EdicaoAnexoTeste(string titulo, string categoria, bool remover = false) { Titulo = titulo; Categoria = categoria; Remover = remover; } }
    public sealed class TesteTexturaService
    {
        private readonly JsonService _json; private readonly AnexoService _anexos;
        public TesteTexturaService(JsonService json, AnexoService anexos) { _json = json; _anexos = anexos; }
        public string Pasta(string raiz, Guid id) { return Path.Combine(raiz, "TestesTextura", id.ToString("D")); } public string Caminho(string raiz, Guid id) { return Path.Combine(Pasta(raiz, id), "teste.json"); } public TesteTexturaCadastro Carregar(string raiz, Guid id) { return _json.Read<TesteTexturaCadastro>(Caminho(raiz, id)); }
        public IReadOnlyList<TesteTexturaCadastro> Listar(string raiz) { var dir = Path.Combine(raiz, "TestesTextura"); var lista = new List<TesteTexturaCadastro>(); if (!Directory.Exists(dir)) return lista; foreach (var arquivo in Directory.GetFiles(dir, "teste.json", SearchOption.AllDirectories)) try { lista.Add(_json.Read<TesteTexturaCadastro>(arquivo)); } catch { } return lista.OrderByDescending(x => x.UltimaEdicaoEm).ToList(); }
        public IReadOnlyList<TesteTexturaCadastro> Pesquisar(string raiz, string termo) { return Listar(raiz).Where(x => Corresponde(x, termo)).ToList(); }
        public static bool Corresponde(TesteTexturaCadastro teste, string termo) { if (string.IsNullOrWhiteSpace(termo)) return false; var campos = new List<string> { teste.Identificacao, teste.NomeAprovado, Situacao(teste.Status), teste.Data.ToString("d"), teste.Observacao }; campos.AddRange(TodosAnexos(teste).Select(x => x.Titulo ?? x.NomeOriginal)); return campos.Any(x => NormalizadorPesquisa.Contem(x ?? string.Empty, termo)); }
        public TesteTexturaCadastro Cadastrar(string raiz, string identificacao, string pastaOrigem, StatusTesteTextura status, string nomeAprovado, string observacao, AnexoPendente imagemObrigatoria, IReadOnlyCollection<AnexoPendente> arquivos)
        {
            if (string.IsNullOrWhiteSpace(identificacao)) throw new InvalidDataException("Informe a identificação do teste."); ValidarTitulo(imagemObrigatoria); foreach (var item in arquivos) ValidarTitulo(item); var teste = new TesteTexturaCadastro { Id = Guid.NewGuid(), Identificacao = identificacao.Trim(), PastaOrigem = pastaOrigem.Trim(), Status = status, NomeAprovado = Limpar(nomeAprovado), Observacao = Limpar(observacao), Imagem = new AnexoCadastro { NomeOriginal = "pendente", NomeInterno = "pendente", CaminhoRelativo = "pendente" }, Data = DateTimeOffset.Now, UltimaEdicaoEm = DateTimeOffset.Now, Responsavel = Environment.UserName, UltimaEdicaoPor = Environment.UserName, Computador = Environment.MachineName }; var pasta = Pasta(raiz, teste.Id); var criada = false;
            try { Directory.CreateDirectory(pasta); criada = true; foreach (var subpasta in new[] { "imagens", "arquivos", "backups" }) Directory.CreateDirectory(Path.Combine(pasta, subpasta)); var evento = new EventoTesteTextura { Tipo = "Teste de textura cadastrado", Observacao = teste.Observacao }; teste.Imagem = _anexos.CopiarParaCadastro(imagemObrigatoria, pasta, evento.Id); evento.Imagens.Add(teste.Imagem); foreach (var pendente in arquivos) { var anexo = _anexos.CopiarParaCadastro(pendente, pasta, evento.Id); if (pendente.Imagem) { teste.Imagens.Add(anexo); evento.Imagens.Add(anexo); } else { teste.Arquivos.Add(anexo); evento.Anexos.Add(anexo); } } teste.Historico.Add(evento); _json.WriteAtomic(Caminho(raiz, teste.Id), teste, Path.Combine(pasta, "backups")); return ValidarRelido(raiz, teste.Id, teste.VersaoCadastro); } catch { if (criada && Directory.Exists(pasta)) Directory.Delete(pasta, true); throw; }
        }
        public TesteTexturaCadastro Atualizar(string raiz, TesteTexturaCadastro baseCarregada, StatusTesteTextura status, string nomeAprovado, string observacao, IReadOnlyCollection<AnexoPendente> pendentes)
        {
            if (string.IsNullOrWhiteSpace(observacao)) throw new InvalidDataException("Informe a observação da atualização."); foreach (var item in pendentes) ValidarTitulo(item); var atual = Carregar(raiz, baseCarregada.Id); ValidarVersao(baseCarregada, atual); var evento = new EventoTesteTextura { Tipo = "Situação atualizada", Observacao = observacao.Trim(), ValorAnterior = Situacao(atual.Status), ValorNovo = Situacao(status) }; if (atual.Status != status) evento.Alteracoes.Add(Alteracao("Situação", Situacao(atual.Status), Situacao(status), observacao)); var nomeNovo = Limpar(nomeAprovado); if (!string.Equals(atual.NomeAprovado, nomeNovo, StringComparison.Ordinal)) evento.Alteracoes.Add(Alteracao("Nome aprovado", atual.NomeAprovado, nomeNovo, observacao)); atual.Status = status; atual.NomeAprovado = nomeNovo; atual.Observacao = observacao.Trim(); var pasta = Pasta(raiz, atual.Id);
            try { foreach (var pendente in pendentes) { var anexo = _anexos.CopiarParaCadastro(pendente, pasta, evento.Id); if (pendente.Imagem) { atual.Imagens.Add(anexo); evento.Imagens.Add(anexo); } else { atual.Arquivos.Add(anexo); evento.Anexos.Add(anexo); } } atual.Historico.Add(evento); PrepararNovaVersao(atual); _json.WriteAtomic(Caminho(raiz, atual.Id), atual, Path.Combine(pasta, "backups")); return ValidarRelido(raiz, atual.Id, atual.VersaoCadastro); } catch { RemoverPastaEvento(pasta, "imagens", evento.Id); RemoverPastaEvento(pasta, "arquivos", evento.Id); throw; }
        }
        public TesteTexturaCadastro Editar(string raiz, TesteTexturaCadastro baseCarregada, string identificacao, string pastaOrigem, string observacaoInicial, string observacaoEdicao, IReadOnlyDictionary<Guid, EdicaoAnexoTeste> edicoesAnexos)
        {
            if (string.IsNullOrWhiteSpace(identificacao)) throw new InvalidDataException("Informe a identificação do teste."); if (string.IsNullOrWhiteSpace(observacaoEdicao)) throw new InvalidDataException("Informe a observação da edição."); var atual = Carregar(raiz, baseCarregada.Id); ValidarVersao(baseCarregada, atual); var alteracoes = new List<AlteracaoCampo>(); Comparar(alteracoes, "Identificação", atual.Identificacao, identificacao.Trim(), observacaoEdicao); Comparar(alteracoes, "Pasta de origem", atual.PastaOrigem, pastaOrigem.Trim(), observacaoEdicao); Comparar(alteracoes, "Observação inicial", atual.Observacao, Limpar(observacaoInicial), observacaoEdicao); atual.Identificacao = identificacao.Trim(); atual.PastaOrigem = pastaOrigem.Trim(); atual.Observacao = Limpar(observacaoInicial); AplicarEdicaoAnexo(atual.Imagem, edicoesAnexos, alteracoes, observacaoEdicao, false); foreach (var anexo in atual.Imagens.ToArray()) if (AplicarEdicaoAnexo(anexo, edicoesAnexos, alteracoes, observacaoEdicao, true)) atual.Imagens.Remove(anexo); foreach (var anexo in atual.Arquivos.ToArray()) if (AplicarEdicaoAnexo(anexo, edicoesAnexos, alteracoes, observacaoEdicao, true)) atual.Arquivos.Remove(anexo); if (alteracoes.Count == 0) throw new InvalidDataException("Nenhuma correção foi informada."); atual.Historico.Add(new EventoTesteTextura { Tipo = "Cadastro do teste corrigido", Observacao = observacaoEdicao.Trim(), Alteracoes = alteracoes }); PrepararNovaVersao(atual); var pasta = Pasta(raiz, atual.Id); _json.WriteAtomic(Caminho(raiz, atual.Id), atual, Path.Combine(pasta, "backups")); return ValidarRelido(raiz, atual.Id, atual.VersaoCadastro);
        }
        public static IReadOnlyList<AnexoCadastro> TodosAnexos(TesteTexturaCadastro teste) { return new[] { teste.Imagem }.Concat(teste.Imagens).Concat(teste.Arquivos).GroupBy(x => x.Id).Select(x => x.First()).ToList(); }
        public static string Situacao(StatusTesteTextura status) { return status == StatusTesteTextura.EmTeste ? "Em teste" : status == StatusTesteTextura.Aprovada ? "Aprovada" : "Reprovada"; }
        private TesteTexturaCadastro ValidarRelido(string raiz, Guid id, int versao) { var relido = Carregar(raiz, id); if (relido.Id != id || relido.VersaoCadastro != versao) throw new InvalidDataException("O teste salvo não passou pela validação final."); return relido; }
        private static void ValidarVersao(TesteTexturaCadastro esperado, TesteTexturaCadastro atual) { if (esperado.VersaoCadastro != atual.VersaoCadastro) throw new InvalidOperationException("O teste foi alterado por outra pessoa. Reabra a ficha."); }
        private static void PrepararNovaVersao(TesteTexturaCadastro teste) { teste.VersaoCadastro++; teste.UltimaEdicaoEm = DateTimeOffset.Now; teste.UltimaEdicaoPor = Environment.UserName; }
        private static void ValidarTitulo(AnexoPendente anexo) { if (string.IsNullOrWhiteSpace(anexo.Titulo)) throw new InvalidDataException("Informe o título de " + anexo.NomeOriginal + "."); }
        private static AlteracaoCampo Alteracao(string campo, string anterior, string novo, string observacao) { return new AlteracaoCampo { Campo = campo, ValorAnterior = anterior, ValorNovo = novo, Observacao = observacao.Trim() }; }
        private static void Comparar(List<AlteracaoCampo> alteracoes, string campo, string anterior, string novo, string observacao) { if (!string.Equals(anterior, novo, StringComparison.Ordinal)) alteracoes.Add(Alteracao(campo, anterior, novo, observacao)); }
        private static bool AplicarEdicaoAnexo(AnexoCadastro anexo, IReadOnlyDictionary<Guid, EdicaoAnexoTeste> edicoes, List<AlteracaoCampo> alteracoes, string observacao, bool permitirRemover) { EdicaoAnexoTeste edicao; if (!edicoes.TryGetValue(anexo.Id, out edicao)) return false; if (edicao.Remover) { if (!permitirRemover) throw new InvalidDataException("A imagem principal obrigatória não pode ser removida."); alteracoes.Add(Alteracao("Anexo", anexo.Titulo ?? anexo.NomeOriginal, "Removido", observacao)); return true; } if (string.IsNullOrWhiteSpace(edicao.Titulo)) throw new InvalidDataException("O título do anexo é obrigatório."); Comparar(alteracoes, "Título do anexo", anexo.Titulo, edicao.Titulo.Trim(), observacao); Comparar(alteracoes, "Categoria do anexo", anexo.Categoria, Limpar(edicao.Categoria), observacao); anexo.Titulo = edicao.Titulo.Trim(); anexo.Categoria = Limpar(edicao.Categoria); return false; }
        private static string Limpar(string valor) { return string.IsNullOrWhiteSpace(valor) ? null : valor.Trim(); } private static void RemoverPastaEvento(string pasta, string categoria, Guid eventoId) { var alvo = Path.Combine(pasta, categoria, eventoId.ToString("D")); if (Directory.Exists(alvo)) Directory.Delete(alvo, true); }
    }
}
